# Uses issue context to add the opened issue to the project
# https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#issues
name: _global - Auto-add issues to project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      # https://github.com/actions/create-github-app-token
      # https://markwiemer.com/software/github/apps/
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      # https://github.com/actions/add-to-project
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/mark-wiemer/projects/2
          github-token: ${{ steps.app-token.outputs.token }}
