# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: vscode/extension CI (Bun)

on:
  push:
    branches: ["main"]
    paths:
      - "packages/vscode/extension/**"
      - ".github/workflows/vscode-extension-node.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "packages/vscode/extension/**"
      - ".github/workflows/vscode-extension-node.yml"
  workflow_dispatch:

jobs:
  build:
    env:
      packageDir: packages/vscode/extension
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - run: bun install
        working-directory: ${{ env.packageDir }}
      - run: bun run validate:ci
        working-directory: ${{ env.packageDir }}
